# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'APPFormwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APPFormwork
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'ZFPlayer'
pod 'MJRefresh'
pod 'FMDB'

end
